const test = require('node:test');
const assert = require('node:assert/strict');
const guardModule = require('../js/workflow/importar-servicio-web/importar-servicio-web-task-context-guard.js');
const fs = require('node:fs');
function control(disabled=false) { const attrs={}; return {disabled,getAttribute:key=>Object.hasOwn(attrs,key)?attrs[key]:null,setAttribute:(key,value)=>{attrs[key]=String(value)},removeAttribute:key=>{delete attrs[key]},attrs}; }
test('captura contexto inmutable y rechaza cambio de tarea', () => { let task=1001; const guard=guardModule.create({currentTaskId:()=>task}); const snapshot=guard.capture({TaskId:1001,ProviderId:'INTEGRACIONSII',ExternalKeys:['A']}); assert.equal(Object.isFrozen(snapshot),true); task=2002; assert.throws(()=>guard.assertCurrent(),/TASK_CONTEXT_MISMATCH/); assert.equal(snapshot.taskId,1001); });
test('bloquea y restaura controles sin perder estado previo', () => { const enabled=control(false), disabled=control(true); const guard=guardModule.create({currentTaskId:()=>1001,controls:[enabled,disabled]}); guard.capture({TaskId:1001}); guard.lock(); assert.equal(enabled.disabled,true); guard.unlock(); assert.equal(enabled.disabled,false); assert.equal(disabled.disabled,true); assert.equal(enabled.getAttribute('aria-disabled'),null); });
test('señal de otra pestaña informa conflicto sin cambiar autoridad', () => { const events=[]; const guard=guardModule.create({currentTaskId:()=>1001,eventTarget:{dispatchEvent:event=>events.push(event)}}); guard.capture({TaskId:1001,IntentId:'intent-1'}); assert.equal(guard.observeTaskSignal({TaskId:2002}),true); assert.equal(guard.snapshot().taskId,1001); assert.equal(events[0].detail.code,'TASK_CONTEXT_MISMATCH'); });
test('UI revalida antes de ejecutar y reutiliza acciones Workflow declaradas', () => { const ui=fs.readFileSync('js/workflow/importar-servicio-web/importar-servicio-web-ui.js','utf8'); const page=fs.readFileSync('workflow/Webworkflow.aspx','utf8'); const registration=fs.readFileSync('workflow/Webworkflow.aspx.vb','utf8'); assert.match(ui,/preflightImport\(fresh\)[\s\S]*taskContextGuard\.lock\(\)[\s\S]*progressAdapter\.execute/); assert.match(ui,/workflow:task-context-changed/); assert.match(ui,/data-workflow-task-action/); assert.match(page,/cerrar esta ventana no detiene ni revierte la importación/); assert.ok((page.match(/data-workflow-task-action="true"/g)||[]).length>=4); assert.ok(registration.indexOf('importarServicioWebTaskContextGuardScript') < registration.indexOf('importarServicioWebUiScript')); });
