import type { AppGuideTourStep } from "../AppGuideTour";

export const APP_VISOR_EMBED_PDF_GUIDE_TOUR_ID = "appvisor-embed-pdf";

export const APP_VISOR_EMBED_PDF_GUIDE_STEPS: AppGuideTourStep[] = [
  {
    id: "pdf-toolbar",
    element: '[data-guide-tour-id="pdf-toolbar"]',
    title: "Toolbar PDF",
    description: "Aqui estan las acciones principales del visor PDF.",
    side: "bottom",
  },
  {
    id: "pdf-thumbnails",
    element: '[data-guide-tour-id="pdf-thumbnails-toggle"]',
    title: "Miniaturas",
    description: "Abre o cierra el panel lateral de paginas del documento.",
    side: "bottom",
  },
  {
    id: "pdf-zoom-out",
    element: '[data-guide-tour-id="pdf-zoom-out"]',
    title: "Reducir zoom",
    description: "Disminuye la escala del documento manteniendo el punto visual actual.",
    side: "bottom",
  },
  {
    id: "pdf-zoom-level",
    element: '[data-guide-tour-id="pdf-zoom-level"]',
    title: "Zoom actual",
    description: "Muestra el porcentaje de escala aplicado al documento.",
    side: "bottom",
  },
  {
    id: "pdf-zoom-in",
    element: '[data-guide-tour-id="pdf-zoom-in"]',
    title: "Aumentar zoom",
    description: "Incrementa la escala del documento.",
    side: "bottom",
  },
  {
    id: "pdf-reset-zoom",
    element: '[data-guide-tour-id="pdf-reset-zoom"]',
    title: "Reset zoom",
    description: "Regresa la escala del visor a 100%.",
    side: "bottom",
  },
  {
    id: "pdf-rotate-left",
    element: '[data-guide-tour-id="pdf-rotate-left"]',
    title: "Rotar izquierda",
    description: "Rota las paginas 90 grados hacia la izquierda.",
    side: "bottom",
  },
  {
    id: "pdf-rotate-right",
    element: '[data-guide-tour-id="pdf-rotate-right"]',
    title: "Rotar derecha",
    description: "Rota las paginas 90 grados hacia la derecha.",
    side: "bottom",
  },
  {
    id: "pdf-signature",
    element: '[data-guide-tour-id="pdf-signature"]',
    title: "Firmas",
    description: "Abre el flujo para agregar una firma al documento cuando la politica lo permite.",
    side: "bottom",
  },
  {
    id: "pdf-lock-signature",
    element: '[data-guide-tour-id="pdf-lock-signature"]',
    title: "Bloquear firma",
    description: "Bloquea o desbloquea las firmas colocadas, segun el estado actual.",
    side: "bottom",
  },
  {
    id: "pdf-delete-signature",
    element: '[data-guide-tour-id="pdf-delete-signature"]',
    title: "Eliminar firma",
    description: "Elimina la firma seleccionada cuando exista una seleccion valida.",
    side: "bottom",
  },
  {
    id: "pdf-print",
    element: '[data-guide-tour-id="pdf-print"]',
    title: "Imprimir",
    description: "Envia el documento al flujo de impresion permitido por el visor.",
    side: "bottom",
  },
  {
    id: "pdf-export",
    element: '[data-guide-tour-id="pdf-export"]',
    title: "Exportar",
    description: "Descarga una copia del documento con los cambios materializados.",
    side: "bottom",
  },
  {
    id: "pdf-help",
    element: '[data-guide-tour-id="pdf-help"]',
    title: "Guia interactiva",
    description: "Vuelve a iniciar este recorrido cuando necesites repasar las acciones del visor.",
    side: "bottom",
  },
  {
    id: "pdf-pagination",
    element: '[data-guide-tour-id="pdf-pagination"]',
    title: "Paginacion",
    description: "Permite avanzar, retroceder o escribir el numero de pagina.",
    side: "top",
  },
  {
    id: "pdf-scroll-top",
    element: '[data-guide-tour-id="pdf-scroll-top"]',
    title: "Ir arriba",
    description: "Regresa al inicio del documento cuando el boton esta visible.",
    side: "left",
  },
];
