import type { RawMenuItem } from "../types/menu";

/**
 * Fallback local del menú cuando no hay conexión a la API.
 */
const menuFallback: RawMenuItem[] = [
  {
    IdMenuPrincipal: 1,
    NombreModulo: "Workflow",
    ValueNode: "WF-WF-01",
    ToltipNode: "Modulo para flujos de trabajo",
    UrlNode: "",
    PageName: "",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "",
    ValueCardConten: "",
    TIpoModulo: "WF",
    AcesoDirecto: 0,
    IdPadre: 0,
    Orden: 1,
    Icono: "",
  },
  {
    IdMenuPrincipal: 11,
    NombreModulo: "Docuarchi Contendor",
    ValueNode: "DA-PR-00",
    ToltipNode: "Contendor de documentos",
    UrlNode: "",
    PageName: "",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "",
    ValueCardConten: "",
    TIpoModulo: "DA",
    AcesoDirecto: 0,
    IdPadre: 0,
    Orden: 2,
    Icono: "",
  },
  {
    IdMenuPrincipal: 15,
    NombreModulo: "Corespondencia",
    ValueNode: "CR-PR-00",
    ToltipNode: "Gestión de la corresponencia",
    UrlNode: "",
    PageName: "",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "",
    ValueCardConten: "",
    TIpoModulo: "RD",
    AcesoDirecto: 0,
    IdPadre: 0,
    Orden: 3,
    Icono: "",
  },
  {
    IdMenuPrincipal: 23,
    NombreModulo: "Gestión documental",
    ValueNode: "GD-PR-00",
    ToltipNode: "Opciones para gestión documental",
    UrlNode: "",
    PageName: "",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 0,
    Orden: 4,
    Icono: "",
  },
  {
    IdMenuPrincipal: 2,
    NombreModulo: "Flujos y tareas prueba",
    ValueNode: "WF-CL-01",
    ToltipNode: "Gestión de flujos y tareas",
    UrlNode: "/workflow/",
    PageName: "Webworkflow.aspx",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "WF-CL-01_card_boton",
    ValueCardConten: "WF-CL-01_card_content",
    TIpoModulo: "WF",
    AcesoDirecto: 1,
    IdPadre: 1,
    Orden: 1,
    Icono: "fa-solid fa-sitemap",
  },
  {
    IdMenuPrincipal: 4,
    NombreModulo: "Reportes de flujos y tareas",
    ValueNode: "WF-RW-03",
    ToltipNode: "Reportes especializados de flujos y tareas",
    UrlNode: "../workflow/",
    PageName: "WebFormReportesWorkflow.aspx",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "../Workflow/WebFormContenedorPageWF.aspx",
    ValueContent: "REPORTES WORKFLOW",
    ValueCard: "WF-RW-03_card_boton",
    ValueCardConten: "",
    TIpoModulo: "WF",
    AcesoDirecto: 0,
    IdPadre: 1,
    Orden: 3,
    Icono: "fa-solid fa-chart-pie",
  },
  {
    IdMenuPrincipal: 5,
    NombreModulo: "Consulta de docmentos",
    ValueNode: "WF-CD-05",
    ToltipNode: "Consulta de gabinetes y documentos en una nueva pestaña del navegador.",
    UrlNode: "../Docuarchi/",
    PageName: "WebFormDaPrincipal.aspx",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "../Workflow/WebFormContenedorPageWF.aspx",
    ValueContent: "CONSULTA DOCUMENTOS",
    ValueCard: "WF-CD-05_card_boton",
    ValueCardConten: "",
    TIpoModulo: "WF",
    AcesoDirecto: 0,
    IdPadre: 1,
    Orden: 4,
    Icono: "fa-solid fa-file-alt",
  },
  {
    IdMenuPrincipal: 13,
    NombreModulo: "Contenedor de Documentos",
    ValueNode: "DA-CLI-01",
    ToltipNode: "Gestión de documentos mediante gabinetes virtuales",
    UrlNode: "../Docuarchi/",
    PageName: "WebFormDaPrincipal.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "DA-CLI-01_card_boton",
    ValueCardConten: "",
    TIpoModulo: "DA",
    AcesoDirecto: 0,
    IdPadre: 11,
    Orden: 1,
    Icono: "fa-regular fa-cabinet-filing",
  },
  {
    IdMenuPrincipal: 18,
    NombreModulo: "Respuestas en espera de aprobación",
    ValueNode: "CR-RP-03",
    ToltipNode: "Respuestas en espera de aprobación",
    UrlNode: "../radicador/",
    PageName: "webformlistasolicitudespormiaprobacion.aspx",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "",
    ValueCardConten: "CR-RP-03_card_boton",
    TIpoModulo: "RD",
    AcesoDirecto: 0,
    IdPadre: 15,
    Orden: 3,
    Icono: "fa-regular fa-stamp",
  },
  {
    IdMenuPrincipal: 24,
    NombreModulo: "Gestión de carpetas y documentos electrónicos",
    ValueNode: "GD-GD-14",
    ToltipNode: "Administre carpetas y archivos electrónicos con opciones de radicación y compartición.",
    UrlNode: "../Gestion/",
    PageName: "WebFormProducionDocumental.aspx",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-GD-14_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 1,
    IdPadre: 23,
    Orden: 1,
    Icono: "fa-regular fa-folders",
  },
  {
    IdMenuPrincipal: 25,
    NombreModulo: "Documentos compartidos",
    ValueNode: "GD-MD-00",
    ToltipNode: "Accede a todos los documentos que has compartido o recibido con otros usuarios.",
    UrlNode: "",
    PageName: "",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 23,
    Orden: 1,
    Icono: "fa-regular fa-files",
  },
  {
    IdMenuPrincipal: 28,
    NombreModulo: "Gestión de expedientes",
    ValueNode: "GD-UD-01",
    ToltipNode: "Crea, organiza, consulta y conserva la información de manera estructurada en expeientes",
    UrlNode: "",
    PageName: "",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-UD-01_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 23,
    Orden: 1,
    Icono: "fa-regular fa-folders",
  },
  {
    IdMenuPrincipal: 31,
    NombreModulo: "Gestión de unidades de conservación",
    ValueNode: "GD-ALM-03",
    ToltipNode: "Gestione unidades de conservación de documentos",
    UrlNode: "",
    PageName: "",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-ALM-03_card_content",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 23,
    Orden: 1,
    Icono: "fa-regular fa-boxes-stacked",
  },
  {
    IdMenuPrincipal: 36,
    NombreModulo: "Gestión de instrumentos",
    ValueNode: "GD-GI-06",
    ToltipNode: "Administre los instrumentos archivísticos como tablas de retención, inventarios y cuadros de clasificación documental.",
    UrlNode: "",
    PageName: "",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 23,
    Orden: 1,
    Icono: "fa-regular fa-gears",
  },
  {
    IdMenuPrincipal: 45,
    NombreModulo: "Migración de Documentos",
    ValueNode: "GD-MR-15",
    ToltipNode: "",
    UrlNode: "",
    PageName: "",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 23,
    Orden: 1,
    Icono: "fa-regular fa-laptop-file",
  },
  {
    IdMenuPrincipal: 48,
    NombreModulo: "Cambio de contraseña",
    ValueNode: "GD-PR-20",
    ToltipNode: "Recuperación y cambio de contraseñas",
    UrlNode: "../Gestion/",
    PageName: "WebFormPaswordGestion.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 23,
    Orden: 100,
    Icono: "fa-regular fa-ke",
  },
  {
    IdMenuPrincipal: 26,
    NombreModulo: "Compartir documentos",
    ValueNode: "GD-MD-15",
    ToltipNode: "Comparte uno o varios documentos con usuarios internos o externos- asignando permisos de lectura - colaboración o revisión.",
    UrlNode: "../Gestion/",
    PageName: "WebFormDocumentoCompartidoOtrosUsuarios.aspx",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-MD-15_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 25,
    Orden: 1,
    Icono: "fa-regular fa-share-from-square",
  },
  {
    IdMenuPrincipal: 27,
    NombreModulo: "Pendientes de revisión",
    ValueNode: "GD-DC-19",
    ToltipNode: "Consulta los documentos que te han compartido y que están pendientes de aprobación o retroalimentación.",
    UrlNode: "../Gestion/",
    PageName: "WebFormDocumentosCompartidosRevision.aspx",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-DC-19_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 1,
    IdPadre: 25,
    Orden: 2,
    Icono: "fa-regular fa-memo-circle-check",
  },
  {
    IdMenuPrincipal: 29,
    NombreModulo: "Registro de expedientes",
    ValueNode: "GD-RU-02",
    ToltipNode: "Registra nuevos expedientes.",
    UrlNode: "../Gestion/",
    PageName: "FormGaAgregarExpediente.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-RU-02_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 28,
    Orden: 1,
    Icono: "fa-regular fa-folder-check",
  },
  {
    IdMenuPrincipal: 30,
    NombreModulo: "Consulta de expedientes",
    ValueNode: "GD-CE-03",
    ToltipNode: "Consulta expedientes existentes y accede a sus documentos asociados",
    UrlNode: "../Gestion/",
    PageName: "WebFormGaGestionExpediente.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-CE-03_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 28,
    Orden: 2,
    Icono: "fa-regular fa-folder-magnifying-glass",
  },
  {
    IdMenuPrincipal: 32,
    NombreModulo: "Registro de unidades",
    ValueNode: "GD-CU-04",
    ToltipNode: "Gestione las unidades disponibles en el sistema",
    UrlNode: "../Gestion/",
    PageName: "WebFormGaGestionUnidadConservacion.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-CU-04_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 31,
    Orden: 1,
    Icono: "fa-regular fa-boxes-packing",
  },
  {
    IdMenuPrincipal: 35,
    NombreModulo: "Gestión topográfica",
    ValueNode: "GD-GT-05",
    ToltipNode: "Gestione la organización topográfica de los documentos.",
    UrlNode: "../Gestion/",
    PageName: "WebFormGatoponimica.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "",
    ValueCardConten: "GD-GT-05_card_boton",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 31,
    Orden: 2,
    Icono: "fa-regular fa-box-arrow-down-magnifying-glass",
  },
  {
    IdMenuPrincipal: 37,
    NombreModulo: "Reportes de gestión",
    ValueNode: "GD-RG-07",
    ToltipNode: "Consulta especializada de gestión documental",
    UrlNode: "",
    PageName: "",
    VisibleNode: 1,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "YES",
    UrlContent: "../radicador/WebFormRadicadoExterno.aspx",
    ValueContent: "REPORTES DE GESTION",
    ValueCard: "GD-RG-07_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 36,
    Orden: 4,
    Icono: "fa-regular fa-table-cells-rows",
  },
  {
    IdMenuPrincipal: 38,
    NombreModulo: "Estructura Orgánica",
    ValueNode: "GD-PR-11",
    ToltipNode: "Gestiona la estructura orgánica",
    UrlNode: "../Gestion/",
    PageName: "WebFormGestionOrganigrama.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-AE-12_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 36,
    Orden: 5,
    Icono: "fa-regular fa-sitemap",
  },
  {
    IdMenuPrincipal: 46,
    NombreModulo: "Migrar formatos y documentos",
    ValueNode: "GD-MR-16",
    ToltipNode: "Migra formatos de documentos asigna expedientes",
    UrlNode: "../Gestion_migracion/",
    PageName: "Web_form_gestion_migracion_documento.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-MR-16_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 45,
    Orden: 1,
    Icono: "fa-regular fa-file-import",
  },
  {
    IdMenuPrincipal: 47,
    NombreModulo: "Consulta documentos migrados",
    ValueNode: "GD-MR-17",
    ToltipNode: "Consulta el historial de documentos migrados",
    UrlNode: "../Gestion_migracion/",
    PageName: "Web_form_consulta_documentos_migrados.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-MR-16_card_content",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 45,
    Orden: 2,
    Icono: "fa-regular fa-file-magnifying-glass",
  },
  {
    IdMenuPrincipal: 49,
    NombreModulo: "Gestión de cuadros de clasificación",
    ValueNode: "GD-AC-06",
    ToltipNode: "Accede al cuadro de clasificación para administrar documentos.",
    UrlNode: "./Gestion/",
    PageName: "WebFormGaadmonclasificacion.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-AC-06_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 83,
    Orden: 1,
    Icono: "fa-regular fa-table-layout",
  },
  {
    IdMenuPrincipal: 50,
    NombreModulo: "Gestión de tablas de retención y valoración",
    ValueNode: "GD-AI-08",
    ToltipNode: "Crea, edita y gestiona tablas de retención y valoración",
    UrlNode: "../Gestion/",
    PageName: "WebFormGaGestionInstrumentos.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-AI-08_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 83,
    Orden: 2,
    Icono: "fa-regular fa-browsers",
  },
  {
    IdMenuPrincipal: 51,
    NombreModulo: "Consulta de Cuadros de Clasificación Documental",
    ValueNode: "GD-CC-07",
    ToltipNode: "Visualiza y explora los cuadros de clasificación documental",
    UrlNode: "../Gestion/",
    PageName: "WebFormGaconsultaclasificacion.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-CC-07_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 83,
    Orden: 3,
    Icono: "fa-regular fa-folder-magnifying-glass",
  },
  {
    IdMenuPrincipal: 52,
    NombreModulo: "Consulta de Tablas de Retención y Valoración Documental",
    ValueNode: "GD-AI-09",
    ToltipNode: "",
    UrlNode: "../Gestion/",
    PageName: "WebFormGaGestionInstrumentos.aspx",
    VisibleNode: 0,
    NodoPlantillaRadicado: "",
    TipoPlantilla: "",
    IdPlantilla: 0,
    UrlExterna: "",
    UrlContent: "",
    ValueContent: "",
    ValueCard: "GD-AI-09_card_boton",
    ValueCardConten: "",
    TIpoModulo: "GD",
    AcesoDirecto: 0,
    IdPadre: 83,
    Orden: 3,
    Icono: "fa-regular fa-box-arrow-down-magnifying-glass",
  },
];

export default menuFallback;
